### ISSUE TITLE
Celluloid::Error after moving to 4.3.2

### ISSUE THREAD

**Issue by wdeviers** [reset/ridley#321]
Howdy,

After moving from a considerably older version of Ridley using Celluloid .14 to 4.3.2 and Celluloid 0.16.0 (-io 0.16.2) I get the following stack trace.  This is on a Sinatra app.  I've tried some of the suggestions like calling Celluloid.boot, but I really have no idea what I'm doing in this regard.

2015-10-27 14:22:18 - Celluloid::Error - Thread pool is not running:
	/home/wdeviers/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:29:in `assert_running'
	/home/wdeviers/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:62:in `block in get'
	/home/wdeviers/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:61:in `synchronize'
	/home/wdeviers/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:61:in `get'
	/home/wdeviers/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:30:in `get_thread'
	/home/wdeviers/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:10:in `initialize'
	/home/wdeviers/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:128:in `new'
	/home/wdeviers/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:128:in `start'
	/home/wdeviers/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:43:in `initialize'
	/home/wdeviers/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid.rb:168:in `new'
	/home/wdeviers/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid.rb:168:in `new'
	/home/wdeviers/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/ridley-4.3.2/lib/ridley.rb:29:in `new'
	griddle.rb:35:in `get_chef_connection'
	griddle.rb:24:in `block in <main>'

In lib/ridley.rb, doing this:

    # @return [Ridley::Client]
    def new(*args)
+      Celluloid.boot
      Client.new(*args)
    end

seems to "Fix" the problem but I doubt this is the correct way to handle it.

**Comment by geewiz** [comment]
I've just changed our code from using Chef-API to using Ridley and ran into the same problem. Our RSpec tests run fine but at the end, we get lots of "Terminating task" warnings.
